import { AgentRecord, TrainingBatch } from "../types";

export const INITIAL_DEMO_RECORDS: AgentRecord[] = [
  {
    id: "agent_demo_1",
    agentName: "Lucía Fernández Morales",
    agentId: "AG-1082",
    campaign: "Atención al Cliente VIP",
    supervisor: "Mariana Gómez (Team Leader VIP)",
    jcc: "Roberto Martínez (JCC Operaciones)",
    trainingName: "Trainer: Calidad, Empatía y Resolución en Primer Contacto (FCR)",
    trainerName: "Carlos Benítez (Lead Trainer)",
    completionDate: "2026-08-10",
    score: 94,
    minPassingScore: 70,
    status: "Aprobado",
    attendancePercentage: 100,
    feedback: "Excelente escucha activa y excelente dominio de herramientas de tipificación. Superó el roleplay con honores.",
    skillsAcquired: ["Escucha Activa", "Manejo de Objeciones", "FCR 95%", "Manejo CRM"],
    needsRetraining: false,
    sourceFileName: "Evaluacion_Trainer_Agosto_2026.xlsx",
  },
  {
    id: "agent_demo_2",
    agentName: "Matías Alejandro Rossi",
    agentId: "AG-1094",
    campaign: "Ventas y Up-Selling",
    supervisor: "Esteban Ramos (Supervisor Comercial)",
    jcc: "Claudia Navarro (JCC Comercial)",
    trainingName: "Trainer: Técnicas de Negociación y Cierre de Ventas",
    trainerName: "Valeria Gómez (Sales Coach)",
    completionDate: "2026-08-11",
    score: 88,
    minPassingScore: 75,
    status: "Aprobado",
    attendancePercentage: 95,
    feedback: "Muy buena asertividad en la presentación de ofertas y manejo de precios.",
    skillsAcquired: ["Cierre de Ventas", "Pitch Comercial", "Manejo de Objeciones"],
    needsRetraining: false,
    sourceFileName: "Evaluacion_Trainer_Agosto_2026.xlsx",
  },
  {
    id: "agent_demo_3",
    agentName: "Esteban Rodrigo Quiroga",
    agentId: "AG-1055",
    campaign: "Soporte Técnico Nivel 1",
    supervisor: "Valeria Rossi (Supervisora Técnica)",
    jcc: "Martín Benavídez (JCC Soporte & IT)",
    trainingName: "Trainer: Diagnóstico Rápido de Redes y Troubleshooting",
    trainerName: "Ing. Diego Albarracín",
    completionDate: "2026-08-09",
    score: 58,
    minPassingScore: 70,
    status: "No Aprobado",
    attendancePercentage: 75,
    feedback: "Tuvo dificultades con los comandos de consola y flujo de escalamiento a Nivel 2. Faltó a la sesión práctica 3.",
    skillsAcquired: ["Conceptos Básicos de Red"],
    needsRetraining: true,
    sourceFileName: "Evaluacion_Trainer_Agosto_2026.xlsx",
  },
  {
    id: "agent_demo_4",
    agentName: "Camila Belén Navarro",
    agentId: "AG-1102",
    campaign: "Atención al Cliente VIP",
    supervisor: "Mariana Gómez (Team Leader VIP)",
    jcc: "Roberto Martínez (JCC Operaciones)",
    trainingName: "Trainer: Calidad, Empatía y Resolución en Primer Contacto (FCR)",
    trainerName: "Carlos Benítez (Lead Trainer)",
    completionDate: "2026-08-10",
    score: 91,
    minPassingScore: 70,
    status: "Aprobado",
    attendancePercentage: 100,
    feedback: "Gran calidez en la modulación de voz y rapidez para navegar la base de conocimiento.",
    skillsAcquired: ["Empatía", "Knowledge Base", "Reducción AHT"],
    needsRetraining: false,
    sourceFileName: "Evaluacion_Trainer_Agosto_2026.xlsx",
  },
  {
    id: "agent_demo_5",
    agentName: "Gonzalo Javier Méndez",
    agentId: "AG-1033",
    campaign: "Cobranzas y Recupero",
    supervisor: "Lucas Benítez (Supervisor Cobranzas)",
    jcc: "Claudia Navarro (JCC Comercial)",
    trainingName: "Trainer: Normativa Legal y Negociación de Deuda",
    trainerName: "Dra. Marcela Sosa",
    completionDate: "2026-08-08",
    score: 62,
    minPassingScore: 70,
    status: "No Aprobado",
    attendancePercentage: 85,
    feedback: "Confusión en los plazos legales de intimación y script de consentimiento. Requiere re-capacitación en módulo 2.",
    skillsAcquired: ["Negociación Básica"],
    needsRetraining: true,
    sourceFileName: "Evaluacion_Trainer_Agosto_2026.xlsx",
  },
  {
    id: "agent_demo_6",
    agentName: "Florencia Jazmín Herrera",
    agentId: "AG-1140",
    campaign: "Onboarding Nuevos Ingresos",
    supervisor: "Patricia Duarte (Supervisora Onboarding)",
    jcc: "Roberto Martínez (JCC Operaciones)",
    trainingName: "Trainer: Inducción Corporativa, Sistemas y Políticas de Seguridad",
    trainerName: "Mariana Torres (HR Trainer)",
    completionDate: "2026-08-12",
    score: 100,
    minPassingScore: 70,
    status: "Aprobado",
    attendancePercentage: 100,
    feedback: "Puntaje perfecto en el examen final. Demostró liderazgo y colaboró guiando a sus compañeros durante el taller.",
    skillsAcquired: ["Políticas de Seguridad", "Uso de CRM", "Cultura Organizacional", "Compliance"],
    needsRetraining: false,
    sourceFileName: "Evaluacion_Trainer_Agosto_2026.xlsx",
  },
  {
    id: "agent_demo_7",
    agentName: "Sebastián Ignacio Ríos",
    agentId: "AG-1077",
    campaign: "Ventas y Up-Selling",
    supervisor: "Esteban Ramos (Supervisor Comercial)",
    jcc: "Claudia Navarro (JCC Comercial)",
    trainingName: "Trainer: Técnicas de Negociación y Cierre de Ventas",
    trainerName: "Valeria Gómez (Sales Coach)",
    completionDate: "2026-08-11",
    score: 72,
    minPassingScore: 75,
    status: "No Aprobado",
    attendancePercentage: 90,
    feedback: "Cerca del umbral de aprobación. Buen tono pero necesita pulir el manejo de rebatimiento de objeciones de costo.",
    skillsAcquired: ["Presentación de Producto", "Escucha"],
    needsRetraining: true,
    sourceFileName: "Evaluacion_Trainer_Agosto_2026.xlsx",
  },
  {
    id: "agent_demo_8",
    agentName: "Valentina Sol Acuña",
    agentId: "AG-1125",
    campaign: "Atención al Cliente VIP",
    supervisor: "Mariana Gómez (Team Leader VIP)",
    jcc: "Roberto Martínez (JCC Operaciones)",
    trainingName: "Trainer: Calidad, Empatía y Resolución en Primer Contacto (FCR)",
    trainerName: "Carlos Benítez (Lead Trainer)",
    completionDate: "2026-08-10",
    score: 85,
    minPassingScore: 80,
    status: "Aprobado",
    passedInRetake: true,
    initialScore: 65,
    retakeScore: 85,
    retakeDetails: "Aprobado en Recuperatorio (Columna V: 85 pts)",
    attendancePercentage: 100,
    feedback: "Aprobó en instancia de recuperatorio con 85 pts (nota inicial: 65 pts). Excelente progreso en el roleplay final.",
    skillsAcquired: ["Desescalamiento de Conflictos", "Calidad NPS", "FCR"],
    needsRetraining: false,
    sourceFileName: "Evaluacion_Trainer_Agosto_2026.xlsx",
  },
  {
    id: "agent_demo_9",
    agentName: "Nicolás Ezequiel Peralta",
    agentId: "AG-1061",
    campaign: "Soporte Técnico Nivel 1",
    supervisor: "Valeria Rossi (Supervisora Técnica)",
    jcc: "Martín Benavídez (JCC Soporte & IT)",
    trainingName: "Trainer: Diagnóstico Rápido de Redes y Troubleshooting",
    trainerName: "Ing. Diego Albarracín",
    completionDate: "2026-08-09",
    score: 82,
    minPassingScore: 80,
    status: "Aprobado",
    passedInRetake: true,
    initialScore: 72,
    retakeScore: 82,
    retakeDetails: "Aprobado en Recuperatorio (Columna W: 82 pts)",
    attendancePercentage: 95,
    feedback: "Aprobó en recuperatorio (Columna W: 82 pts). Resolvió satisfactoriamente los casos prácticos de conectividad.",
    skillsAcquired: ["Troubleshooting", "Diagnóstico de Redes", "SLA 15min"],
    needsRetraining: false,
    sourceFileName: "Evaluacion_Trainer_Agosto_2026.xlsx",
  },
  {
    id: "agent_demo_10",
    agentName: "Agustina Mailén Castro",
    agentId: "AG-1134",
    campaign: "Onboarding Nuevos Ingresos",
    supervisor: "Patricia Duarte (Supervisora Onboarding)",
    jcc: "Roberto Martínez (JCC Operaciones)",
    trainingName: "Trainer: Inducción Corporativa, Sistemas y Políticas de Seguridad",
    trainerName: "Mariana Torres (HR Trainer)",
    completionDate: "2026-08-12",
    score: 78,
    minPassingScore: 70,
    status: "Aprobado",
    attendancePercentage: 100,
    feedback: "Aprobada. Muestra buena actitud y asimilación rápida de la normativa de seguridad de la información.",
    skillsAcquired: ["Compliance", "Manejo de Datos", "Sistemas Internos"],
    needsRetraining: false,
    sourceFileName: "Evaluacion_Trainer_Agosto_2026.xlsx",
  },
  {
    id: "agent_demo_11",
    agentName: "Lucas Damián Romero",
    agentId: "AG-1019",
    campaign: "Cobranzas y Recupero",
    supervisor: "Lucas Benítez (Supervisor Cobranzas)",
    jcc: "Claudia Navarro (JCC Comercial)",
    trainingName: "Trainer: Normativa Legal y Negociación de Deuda",
    trainerName: "Dra. Marcela Sosa",
    completionDate: "2026-08-08",
    score: 84,
    minPassingScore: 70,
    status: "Aprobado",
    attendancePercentage: 95,
    feedback: "Buen manejo de acuerdos de pago escalonados y cumplimiento riguroso de normativas.",
    skillsAcquired: ["Negociación de Deuda", "Normativa Legal", "Manejo de Objeciones"],
    needsRetraining: false,
    sourceFileName: "Evaluacion_Trainer_Agosto_2026.xlsx",
  },
  {
    id: "agent_demo_12",
    agentName: "Micaela Soledad Paez",
    agentId: "AG-1089",
    campaign: "Soporte Técnico Nivel 1",
    supervisor: "Valeria Rossi (Supervisora Técnica)",
    jcc: "Martín Benavídez (JCC Soporte & IT)",
    trainingName: "Trainer: Diagnóstico Rápido de Redes y Troubleshooting",
    trainerName: "Ing. Diego Albarracín",
    completionDate: "2026-08-09",
    score: 65,
    minPassingScore: 70,
    status: "No Aprobado",
    attendancePercentage: 80,
    feedback: "Le faltó tiempo en la prueba práctica de configuración DNS y DHCP. Recomendado taller de refuerzo de 2 horas.",
    skillsAcquired: ["Atención al Usuario"],
    needsRetraining: true,
    sourceFileName: "Evaluacion_Trainer_Agosto_2026.xlsx",
  },
];

export const INITIAL_BATCH: TrainingBatch = {
  id: "batch_demo_initial",
  fileName: "Planilla_Consolidada_Trainers_Agosto.xlsx",
  fileType: "demo",
  uploadDate: "2026-08-12",
  totalAgents: 12,
  approvedCount: 8,
  failedCount: 4,
  averageScore: 79,
  trainingTopic: "Programa Integral de Capacitaciones Operativas & Trainers",
  trainer: "Equipo de Capacitación y Calidad",
  aiSummary:
    "Se evaluaron 12 agentes en 5 módulos especializados de formación. El 66.7% de los agentes aprobó satisfactoriamente los estándares de calidad y conocimientos técnicos. Se identificaron desempeños sobresalientes en Onboarding y Atención VIP, mientras que en Soporte Técnico y Cobranzas se requiere una sesión de refuerzo en resolución práctica y marco normativo.",
  aiRecommendations: [
    "Programar un taller práctico de 2 horas para los 2 agentes no aprobados de Soporte Técnico enfocado en configuración de redes.",
    "Alinear con el Trainer de Ventas la nivelación sobre rebatimiento de objeciones para superar el estándar del 75%.",
    "Emitir de inmediato los certificados oficiales a los 8 agentes aprobados para validar su habilitación operativa.",
    "Implementar evaluaciones formativas a mitad de curso para detectar rezagos antes del examen final.",
  ],
  records: INITIAL_DEMO_RECORDS,
};
